export type StackGroup = {
  id: string;
  label: string;
  items: string[];
};

export const stackGroups: StackGroup[] = [
  {
    id: "frontend",
    label: "FRONTEND",
    items: [
      "React 19",
      "Next.js 16",
      "Vue 3",
      "TypeScript",
      "JavaScript ES6+",
      "Tailwind v4",
      "shadcn/ui",
      "Force UI",
      "Zustand",
      "Redux Toolkit",
      "React Hook Form",
      "Zod",
      "Lingui i18n",
      "PrimeVue",
      "SASS / SCSS",
      "Bootstrap",
    ],
  },
  {
    id: "backend",
    label: "BACKEND",
    items: [
      "Laravel 10",
      "PHP 8+",
      "Eloquent ORM",
      "Prisma",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "REST APIs",
      "JWT Auth",
      "OAuth2",
      "WebSockets",
      "Firebase",
      "Supabase",
      "Edge Runtime",
    ],
  },
  {
    id: "wordpress",
    label: "WORDPRESS",
    items: [
      "Plugin Development",
      "Theme Development",
      "Gutenberg Blocks",
      "WPCS",
      "REST API",
      "Hooks & Filters",
      "Abilities API",
      "MCP Adapter",
      "Multisite",
      "Custom Post Types",
      "ConvertPro / UAVC",
    ],
  },
  {
    id: "ai",
    label: "AI / LLMs",
    items: [
      "Claude API",
      "OpenRouter",
      "Groq",
      "Google Gemini",
      "Llama 3.3 70B",
      "RAG",
      "Function Calling",
      "Vector Search · sql.js",
      "Prompt Caching",
      "Streaming",
    ],
  },
  {
    id: "motion",
    label: "MOTION / UI",
    items: [
      "GSAP + ScrollTrigger",
      "Motion (motion/react)",
      "Lenis Smooth Scroll",
      "Framer Motion",
      "React Flow v12",
      "split-type",
      "next-themes",
      "Recharts",
    ],
  },
  {
    id: "tooling",
    label: "TOOLING",
    items: [
      "Playwright",
      "Vitest",
      "Jest",
      "Storybook",
      "Vite",
      "Webpack",
      "Turbopack",
      "Vercel",
      "Cloudflare",
      "GitHub Actions",
      "Postman",
      "Chrome DevTools",
      "Figma",
      "Agile / Scrum",
    ],
  },
];
